In [1]:
import numpy as np
import pandas as pd
data = np.array([[3, 7],
                 [-4, -6],
                 [1, -1],
                 [7, 8],
                 [-4, -1],
                 [-3, -7]])
dataframe = pd.DataFrame(data, columns=['x1', 'x2'])

In [2]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
dataScaled = scaler.fit_transform(dataframe)

In [3]:
## Approach 1
c1 = dataframe.x1
c2 = dataframe.x2
np.cov(c1, c2)

array([[20., 25.],
       [25., 40.]])

In [12]:
## Approach 2
covarianceMatrix = dataframe.T @ dataframe / 5
covarianceMatrix

x1    x2
x1  20.0  25.0
x2  25.0  40.0

In [5]:
## Approach 3
np.sum(c1 * c2)/5

25.0

##  Calculating the Eigen Values and Eigen Vectors

In [6]:
eigenValues, eigenVectors = np.linalg.eig(covarianceMatrix)

In [7]:
eigenValues

array([ 3.07417596, 56.92582404])

In [8]:
eigenVectors

array([[-0.82806723, -0.56062881],
       [ 0.56062881, -0.82806723]])

## Calculating the new features Or Principal Components

In [13]:
dataframe

x1  x2
0   3   7
1  -4  -6
2   1  -1
3   7   8
4  -4  -1
5  -3  -7

In [16]:
## PC1 - Contains the maximum information of the original two features that you have
PC1 = dataframe @ eigenVectors[:, 0]  # use highest Eigen value
## PC2
PC2 = dataframe @ eigenVectors[:, 1] # use second highest Eigen value

In [14]:
PC1

0    1.440200
1   -0.051504
2   -1.388696
3   -1.311440
4    2.751640
5   -1.440200
dtype: float64

In [15]:
PC2

0    -7.478357
1     7.210919
2     0.267438
3   -10.548940
4     3.070582
5     7.478357
dtype: float64